version: '2'
services:
  printit.prince:
    build:
      context: .
      dockerfile: Dockerfile.prince
    volumes:
      - ./Rakefile:/home/app/Rakefile
      - ./config.ru:/home/app/config.ru
      - ./config:/home/app/config
      - ./lib:/home/app/lib
      - ./public:/home/app/public
      - ./spec:/home/app/spec
      - ./tasks:/home/app/tasks
      - ./webspicy:/home/app/webspicy
    ports:
      - "80:80"
  printit.weasyprint:
    build:
      context: .
      dockerfile: Dockerfile.weasyprint
    volumes:
      - ./Rakefile:/home/app/Rakefile
      - ./config.ru:/home/app/config.ru
      - ./config:/home/app/config
      - ./lib:/home/app/lib
      - ./public:/home/app/public
      - ./spec:/home/app/spec
      - ./tasks:/home/app/tasks
      - ./webspicy:/home/app/webspicy
    ports:
      - "80:80"
